steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/btc-worker', '-f', 'docker/worker.Dockerfile', '.']
images:
- 'gcr.io/$PROJECT_ID/btc-tactical-worker'
timeout: '1200s'
